import Navigation from "@/components/Navigation";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import Image from "next/image";

const eudoxus = localFont({
  src: [
    { path: "../fonts/EudoxusSans-ExtraLight.woff2", weight: "200" },
    { path: "../fonts/EudoxusSans-Light.woff2", weight: "300" },
    { path: "../fonts/EudoxusSans-Regular.woff2", weight: "400" },
    { path: "../fonts/EudoxusSans-Medium.woff2", weight: "500" },
    { path: "../fonts/EudoxusSans-Bold.woff2", weight: "700" },
    { path: "../fonts/EudoxusSans-ExtraBold.woff2", weight: "800" },
  ],
});

export const metadata: Metadata = {
  title: "Metaverse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${eudoxus.className} relative overflow-hidden`}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
